apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: el-nodejs
  namespace: contact-walid-labidi-dev
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-push
      bindings:
        - ref: github-push-binding
      template:
        ref: nodejs-trigger-template

