apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: contact-walid-labidi-dev
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.url)
    - name: git-revision
      value: $(body.ref)

